services:

# -----------------------------------------------------------------------------------------------------
# HoloPlay
# -----------------------------------------------------------------------------------------------------
  holoplay:
    image: spout8301/holoplay:1.12.1
    container_name: holoplay
    restart: unless-stopped
    privileged: true
    ports:
      - 3398:3000
    network_mode: "nginx-proxy-manager_npm"
# -----------------------------------------------------------------------------------------------------
