services:

# -----------------------------------------------------------------------------------------------------
# VSCodium
# -----------------------------------------------------------------------------------------------------
  vscodium:
    image: lscr.io/linuxserver/vscodium:latest
    container_name: vscodium
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - DRINODE=/dev/dri/renderD128
      - CUSTOM_USER=fnxusa
      - PASSWORD=${PASSWORD}
    volumes:
      - ./config:/config
    ports:
      - 3020:3000
      - 3021:3001
    shm_size: "2gb"
    devices:
      - /dev/dri:/dev/dri
    network_mode: "nginx-proxy-manager_npm"
# -----------------------------------------------------------------------------------------------------
