services:

# -----------------------------------------------------------------------------------------------------
# Memos
# -----------------------------------------------------------------------------------------------------
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - 5230:5230
    volumes:
#      - ./memos-data:/usr/local/memos
      - ./memos-var:/var/opt/memos
    network_mode: "nginx-proxy-manager_npm"
# -----------------------------------------------------------------------------------------------------
