services:

# -----------------------------------------------------------------------------------------------------
# qBittorrent
# -----------------------------------------------------------------------------------------------------
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - ./Torrents/Monitored:/monitored
      - ./Torrents/Completed:/downloads
      - ./Torrents/Completed/Movies:/downloads/Movies
      - ./Torrents/Completed/TV Shows:/downloads/TV Shows
      - ./Torrents/Completed/Anime:/downloads/Anime
      - ./Torrents/Completed/Music:/downloads/Music
      - ./Torrents/Completed/Apps:/downloads/Apps
      - ./Torrents/temp:/temp
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 52555:52555
      - 52555:52555/udp
      - 8080:8080
    network_mode: "nginx-proxy-manager_npm"
# -----------------------------------------------------------------------------------------------------
