services:

# -----------------------------------------------------------------------------------------------------
# Syncthing
# -----------------------------------------------------------------------------------------------------
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - UMASK_SET=022
    volumes:
      - ./config:/config
      - ./data1:/data1
      - ./data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    network_mode: "nginx-proxy-manager_npm"
# -----------------------------------------------------------------------------------------------------
