services:

# -----------------------------------------------------------------------------------------------------
# Tautulli for Plex
# -----------------------------------------------------------------------------------------------------
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./config:/config
      - ./logs:/logs
    ports:
      - 8181:8181
    network_mode: "nginx-proxy-manager_npm"
# -----------------------------------------------------------------------------------------------------
