services:

# -----------------------------------------------------------------------------------------------------
# Snapdrop
# -----------------------------------------------------------------------------------------------------
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./config:/config
    ports:
      - 8011:80
      - 44399:443
    network_mode: "nginx-proxy-manager_npm"
# -----------------------------------------------------------------------------------------------------
