services:

# -----------------------------------------------------------------------------------------------------
# Minecraft Server
# -----------------------------------------------------------------------------------------------------
  mc:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
    network_mode: "nginx-proxy-manager_npm"
# -----------------------------------------------------------------------------------------------------
